services:
  postgres:
    image: postgres:18.4
    environment:
    - POSTGRES_DB=sanguebom
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
    - "${DB_PORT}:5432"
    networks:
      - sanguebom-network
    env_file:
      - .env
networks:
  sanguebom-network:
    driver: bridge
